spring.config.import=optional:file:.env[.properties]

spring.application.name=dat

server.port=8086

#MySQL Database Connection
spring.datasource.url=${LOCAL_DB_URL}
spring.datasource.username=${LOCAL_DB_USERNAME}
spring.datasource.password=${LOCAL_DB_PASSWORD}

#PostgreSQL Database Connection
#spring.datasource.url=${LOCAL_DB_POSTGRES_URL}
#spring.datasource.username=${LOCAL_DB_POSTGRES_USERNAME}
#spring.datasource.password=${LOCAL_DB_POSTGRES_PASSWORD}

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update

#JWT Configuration
jwt.secret.string=${JWT_SECRET}
jwt.expiration.time=${JWT_EXPIRATION_TIME}